n=int(input("enter the first number:"))
s=int(input("enter seconf number:"))
print("Addition of these numbers are",n+s)
print("  subtraction of these numbers are",n-s)
print("  multiplication of these numbers are",n*s)
print("  division of these numbers are",n/s)